title: SOLUÇÕES EMPRESARIAIS
url: "https://jsahtest.herokuapp.com/"
baseurl:
google_analytics_key: UA-180939230-1
google_maps_javascript_api_key:
disqus_shortname:

# Default description in social shares for the jekyll-seo-tag gem
description: JSAH SOLUÇÕES EMPRESARIAIS, certidões imobiliarias, certidões, imobiliárias, administrativas, forenses, consultoria fiscal, tributaria.

# Author details for the jekyll-seo-tag gem
author:
  name: JSAH SOLUÇÕES EMPRESARIAIS
  email: contato@jsah.com.br
  twitter:

# Social details for the jekyll-seo-tag gem
social:
  name: JSAH SOLUÇÕES EMPRESARIAIS
  links:
    - https://br.linkedin.com/in/jsah-solu%C3%A7%C3%B5es-empresariais-ltda-789ab41b8

timezone: Etc/UTC

collections:
  staff_members:
    output: false
  clients:
    output: true

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

jekyll-archives:
  enabled:
    - "categories"

plugins:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-archives"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 960
          height: 2000
  - scope:
      path: ""
      type: "clients"
    values:
      layout: "client"
      _options:
        image_path:
          width: 2000
          height: 2000
  - scope:
      path: ""
      type: "staff_members"
    values:
      _options:
        image_path:
          width: 600
          height: 600
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
